#!/usr/bin/perl
#
# A Pythagorean triplet is a set of three natural numbers, a < b < c,
# for which,
#
#     a^(2) + b^(2) = c^(2)
#
# For example, 3^(2) + 4^(2) = 9 + 16 = 25 = 5^(2).
#
# There exists exactly one Pythagorean triplet for which a + b + c = 1000.
# Find the product abc.

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

my $TARGET = shift // 1000;

OUTER:
for (my $a = 1; $a < $TARGET; $a ++) {
    my $a2 = $a ** 2;
    for (my $b = $a; $b < $TARGET; $b ++) {
        my $c = $TARGET - $a - $b;
        next OUTER if $c < $b;
        if ($a2 + $b ** 2 == $c ** 2) {
            say $a * $b * $c;
            exit;
        }
    }
}


__END__
