#!/usr/bin/perl
#
# The sum of the squares of the first ten natural numbers is,
#     1^(2) + 2^(2) + ... + 10^(2) = 385
#
# The square of the sum of the first ten natural numbers is,
#     (1 + 2 + ... + 10)^(2) = 55^(2) = 3025
#
# Hence the difference between the sum of the squares of the first ten
# natural numbers and the square of the sum is 3025 − 385 = 2640.
#
# Find the difference between the sum of the squares of the first one
# hundred natural numbers and the square of the sum.
#

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

my $MAX = shift // 100;

my $sum_of_squares = 0;
my $sum            = 0;

for my $n (1 .. $MAX) {
    $sum            += $n;
    $sum_of_squares += $n ** 2;
}

my $square_of_sum = $sum ** 2;

say $square_of_sum - $sum_of_squares;


__END__
