#!/usr/bin/perl
#
# n! means n × (n − 1) × ... × 3 × 2 × 1
#
# Find the sum of the digits in the number 100!

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

use Math::BigInt;

my $NUMBER = shift // 100;

my $sum  = 0;
   $sum += $_ for split // => Math::BigInt -> new ($NUMBER) -> bfac;

say $sum;

__END__
