#!/usr/bin/perl
#
# Find the unique positive integer whose square has the form
# 1_2_3_4_5_6_7_8_9_0, where each “_” is a single digit.
#

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

for (my $n = 319421990;; $n += 10) {
    my $s = $n * $n;
    if ($s =~ /^1.2.3.4.5.6.7.8.9.0$/) {
        say $n;
        exit;
    }
}


__END__
