#!/usr/bin/perl
#
# A common security method used for online banking is to ask the user for
# three random characters from a passcode. For example, if the passcode
# was 531278, they may asked for the 2nd, 3rd, and 5th characters; the
# expected reply would be: 317.
# 
# The text file, keylog.txt, contains fifty successful login attempts.
# 
# Given that the three characters are always asked for in order, analyse
# the file so as to determine the shortest possible secret passcode of
# unknown length.
# 

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

my @codes = `cat Data/keylog.txt` =~ /(\d\d\d)/g;
my @pats  = map {/(.)(.)(.)/; qr /$1.*$2.*$3/} @codes;

OUTER:
for (my $n = '10000000';; $n ++) {
    foreach my $p (@pats) {
        next OUTER unless $n =~ /$p/;
    }
    say $n;
    exit;
}


__END__
