#!/usr/bin/perl
#
# Let d(n) be defined as the sum of proper divisors of n (numbers less
# than n which divide evenly into n).
# If d(a) = b and d(b) = a, where a != b, then a and b are an amicable pair
# and each of a and b are called amicable numbers.
#
# For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22,
# 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are
# 1, 2, 4, 71 and 142; so d(284) = 220.
#
# Evaluate the sum of all the amicable numbers under 10000.
#

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

use Math;
use List::Util '/./';

my $MAX = shift // 10_000;

my %amicable;

for (my $n = 1; $n < $MAX; $n ++) {
    my @divs = divisors $n;
    pop @divs;
    my $sum = sum @divs;
    $amicable {$n} = $sum // 0;
}
my $sum;
while (my ($n, $a) = each %amicable) {
    $sum += $n if $n != $a && ($amicable {$a} // -1) == $n;
}

say $sum;

__END__
