#!/usr/bin/perl

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

use Math;

# 
# It is possible to write five as a sum in exactly six different ways:
# 
#     4 + 1
#     3 + 2
#     3 + 1 + 1
#     2 + 2 + 1
#     2 + 1 + 1 + 1
#     1 + 1 + 1 + 1 + 1
# 
# How many different ways can one hundred be written as a sum of at least
# two positive integers?
# 


say part_num (100) - 1;


__END__
Answer: 190569291
