#!/usr/bin/perl
#
# You are given the following information, but you may prefer to do some
# research for yourself.
#
#    * 1 Jan 1900 was a Monday.
#    * Thirty days has September,
#      April, June and November.
#      All the rest have thirty-one,
#      Saving February alone,
#      Which has twenty-eight, rain or shine.
#      And on leap years, twenty-nine.
#    * A leap year occurs on any year evenly divisible by 4, but not
#      on a century unless it is divisible by 400.
#
# How many Sundays fell on the first of the month during the twentieth
# century (1 Jan 1901 to 31 Dec 2000)?


use 5.010;

use strict;
use warnings;
no warnings 'syntax';

use Date::Calc 'Day_of_Week';

my $count = 0;

for my $year (1901 .. 2000) {
    for my $month (1 .. 12) {
        $count ++ if 7 == Day_of_Week $year, $month, 1;
    }
}

say $count;

__END__
