#!/usr/bin/perl
#
# If we list all the natural numbers below 10 that are multiples of 3 or 5,
# we get 3, 5, 6 and 9. The sum of these multiples is 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.
#

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

my $MAX = shift // 1000;
my $sum = 0;

for (my $n = 1; $n < $MAX; $n ++) {
    $sum += $n unless $n % 3 && $n % 5;
}

say $sum;

__END__
