#!/usr/bin/perl

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

#
# A permutation is an ordered arrangement of objects. For example,
# 3124 is one possible permutation of the digits 1, 2, 3 and 4. If all of
# the permutations are listed numerically or alphabetically, we call it
# lexicographic order. The lexicographic permutations of 0, 1 and 2 are:
# 
#     012   021   102   120   201   210
# 
# What is the millionth lexicographic permutation of the digits
# 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9?
#

#
# Brute force is fast enough.
#

use Algorithm::Permute qw [permute];

my @digits = (0 .. 9);

local $" = "";

my @list;
permute {push @list => "@digits"} @digits;

@list = sort @list;

say $list [999_999];

__END__
# Answer: 2783915460
