#!/usr/bin/perl
#
# The n^(th) term of the sequence of triangle numbers is given by,
# t_(n) = ½n(n+1); so the first ten triangle numbers are:
#
#    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# By converting each letter in a word to a number corresponding to its
# alphabetical position and adding these values we form a word value. For
# example, the word value for SKY is 19 + 11 + 25 = 55 = t_(10). If the
# word value is a triangle number then we shall call the word a triangle word.
#
# Using words.txt (right click and 'Save Link/Target As...'), a 16K text
# file containing nearly two-thousand common English words, how many are
# triangle words?
#

use 5.010;

use strict;
use warnings;
no warnings 'syntax';

use List::Util '/./';

my @words = `cat Data/words.txt` =~ /([A-Z]+)/g;

my $t = 0;
my %triangle;
for my $n (1 .. 20) {
    $t += $n;
    $triangle {$t} = 1;
}

my $count = 0;
foreach my $word (@words) {
    my $value = sum map {1 + ord ($_) - ord ('A')} split // => $word;
    $count ++ if $triangle {$value}
}

say $count;


__END__
